# Generated by Django 3.0.4 on 2020-09-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
